# Generated by Django 5.1.1 on 2024-10-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_created_at_student_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='students/images'),
        ),
    ]
