# Generated by Django 5.1.1 on 2024-10-05 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_image'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracks.track'),
        ),
    ]
